### ISSUE TITLE
Handle TypeErrors in promise

### ISSUE THREAD

**Issue by fleischie** [mamal72/node-yahoo-weather#3]
Hi.

Just a short question, whether it's possible to handle the potential TypeErrors, if `json.query.results` is null?

It's nothing serious, as it only provides a short `console.error` call, I just wanted to ask. 😄

**Comment by mamal72** [comment]
Hi. Thanks for filling the issue. 
You are right. I wasn't aware of such case! As I just checked, there will be some cases with `null` in `results`.

It can be fixed in 2 ways:
- Checking results and make sure it's not `null`.
- Checking the sibling key of `results` named `count` and make sure it's more than `0`.

I can fix it in the next few days. You can also send a PR if you want to see it sooner. 🙂

**Comment by mamal72** [comment]
[This](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20u=%27c%27%20AND%20woeid%20in%20%28select%20woeid%20from%20geo.places%281%29%20where%20text=%22nonononono%22%29&format=json) is a failing case with `null` as `results`.

**Comment by fleischie** [comment]
@mamal72 I have time today, so I might just check it out and submit a PR. 👍 😄

**Comment by fleischie** [comment]
Closing, as I opened a PR. 😃 Check this bad boy: #4 😁
